title = "Ruan"
baseURL = "https://rebirthmonkey.github.io"
languageCode = "en-us"
theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Ruan"
    weight = 1
    contentDir = "content/en"
  [languages.cn]
    title = "贺阮"
    weight = 2
    contentDir = "content/cn"

[author]
  name = "HE Ruan"
  homepage = "www.linkedin.com/in/ruan-he"
